#!/bin/sh
# ---------------------------------------------------------------------------
# TEST-REM
#
# This file runs an acceptance test for Remind.  To use it, type:
#      sh test-rem  OR make test
# in the build directory.
#
# This file is part of REMIND.
# Copyright (C) 1992, 1993 by David F. Skoll
# ---------------------------------------------------------------------------

TEST_GETENV="foo bar baz" ; export TEST_GETENV
./remind -e -dxte ./test.rem 16 feb 1991 > ./test.out
cmp -s ./test.out ./test.cmp
if [ "$?" = "0" ]; then
   echo "Remind:  Acceptance test PASSED"
   exit 0
else
   echo "Remind:  Acceptance test FAILED"
   echo ""
   echo "Examine the file test.out to see where it differs from the"
   echo "reference file test.cmp."
   exit 1
fi
